<a href="https://colab.research.google.com/github/idarwati/BelajarPython/blob/main/PythonMasterclass/Belajar_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Python Masterclass Indonesia**
materi 1-17

In [ ]:
2*3

6

In [ ]:
bil1 = 3.6

In [ ]:
bil1

3.6

In [ ]:
type (bil1)

float

In [ ]:
6/2

3.0

In [ ]:
type (6/2)

float

In [ ]:
6%2

0

In [ ]:
10%3

1

In [ ]:
2**2

4

In [ ]:
2*2

4

In [ ]:
2 + 10 * 3 + 4 * 8 + 5

69

In [ ]:
(2 + 10) * (3 + 4) * (8 + 5)

1092

In [ ]:
a = 3

In [ ]:
item_saya = 15

In [ ]:
item_saya = ["ikan", "ayam", "bebek"]

In [ ]:
item_saya

['ikan', 'ayam', 'bebek']

In [ ]:
item_saya[2]

'bebek'

In [ ]:
item_saya[0:2]

['ikan', 'ayam']

In [ ]:
"Makassar"

'Makassar'

In [ ]:
"Makassar" [::-1]

'rassakaM'

In [ ]:
"Makassar" [1:-1:2]

'aas'

In [ ]:
item = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
item

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
item[2::]

[3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
item[1::3]

[2, 5, 8]

In [ ]:
nama = "Idar"

In [ ]:
nama*3

'IdarIdarIdar'

In [ ]:
nama + " M"

'Idar M'

In [ ]:
nama + ' sedang belajar Python'

'Idar sedang belajar Python'

In [ ]:
nama.upper()

'IDAR'

In [ ]:
nama = nama + " sedang belajar python"

In [ ]:
nama

'Idar sedang belajar python'

In [ ]:
nama.split()

['Idar', 'sedang', 'belajar', 'python']

In [ ]:
nama.split('a')

['Id', 'r sed', 'ng bel', 'j', 'r python']

In [ ]:
nama2 = [1, 2, 3, 4, 5]

In [ ]:
type(nama)

str

In [ ]:
type(nama2)

list

In [ ]:
print('Tingkat pendidikan dasar {} {} {}'.format("SD", "SMP", "SMA"))

Tingkat pendidikan dasar SD SMP SMA


In [ ]:
print('Tingkat pendidikan dasar {1} {2} {0}'.format("SD", "SMP", "SMA"))

Tingkat pendidikan dasar SMP SMA SD


In [ ]:
print('Tingkat pendidikan dasar {c} {a} {b}'.format(a="SD", b="SMP", c="SMA"))

Tingkat pendidikan dasar SMA SD SMP


In [ ]:
phi=22/7

In [ ]:
phi

3.142857142857143

In [ ]:
print('Untuk menghitung luas lingkaran, gunakanlah phi = {}'.format(phi))

Untuk menghitung luas lingkaran, gunakanlah phi = 3.142857142857143


In [ ]:
luas1=667.9

In [ ]:
luas2=998.7

In [ ]:
print('Luas tanah yang dimiliki Pak Budi adalah {a} {b}'.format(a=luas1, b=luas2))

Luas tanah yang dimiliki Pak Budi adalah 667.9 998.7


In [ ]:
keranjang = [1, 2.3, 'jeruk']

In [ ]:
len(keranjang)

3

In [ ]:
for i in range(len(keranjang)):
    print(keranjang[i])

1
2.3
jeruk


In [ ]:
keranjang[1] = 'mangga'

In [ ]:
keranjang

[1, 'mangga', 'jeruk']

In [ ]:
keranjang.append('pisang')

In [ ]:
keranjang

[1, 'mangga', 'jeruk', 'pisang']

In [ ]:
buah_lagi = ['anggur', 'nanas', 'jeruk bali', 'apel washington']

In [ ]:
keranjang = keranjang + buah_lagi

In [ ]:
keranjang

[1,
 'mangga',
 'jeruk',
 'pisang',
 'anggur',
 'nanas',
 'jeruk baliapel washington',
 ['anggur', 'nanas', 'jeruk baliapel washington'],
 'anggur',
 'nanas',
 'jeruk bali',
 'apel washington',
 'anggur',
 'nanas',
 'jeruk bali',
 'apel washington']

In [ ]:
len(keranjang)

17

In [ ]:
keranjang.append(buah_lagi)

In [ ]:
keranjang

[1,
 'mangga',
 'jeruk',
 'pisang',
 'anggur',
 'nanas',
 'jeruk baliapel washington',
 ['anggur', 'nanas', 'jeruk baliapel washington']]

In [ ]:
baru = [1, 2, 3, 4, 5, 6]

In [ ]:
baru

[1, 2, 3, 4]

In [ ]:
baru.pop()

6

In [ ]:
baru.pop(1)

2

In [ ]:
baru

[1, 3, 4]

In [ ]:
baru_lagi = baru.pop()

In [ ]:
baru_lagi

4

In [ ]:
baru

[1, 3]

In [ ]:
isi = [1, 2, 3, 4, 5,[6,7,8]]

In [ ]:
isi

[1, 2, 3, 4, 5, [6, 7, 8]]

In [ ]:
isi[2]

3

In [ ]:
isi[2:]

[3, 4, 5, [6, 7, 8]]

In [ ]:
for i in 'saya belajar python':
    print(i)

s
a
y
a
 
b
e
l
a
j
a
r
 
p
y
t
h
o
n


In [ ]:
for i in 'saya belajar python':
    print(i, end='')

saya belajar python

In [ ]:
angka = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
for isi in angka:
    print(isi)

1
2
3
4
5
6
7
8
9
10


In [ ]:
jumlah = 0

In [ ]:
for isi in angka:
    jumlah = jumlah + isi
    print(jumlah)

1
3
6
10
15
21
28
36
45
55


In [ ]:
for isi in angka:
    jumlah = jumlah + isi
    print('Hasil penjumlahan pada iterator ke-{} adalah {}'.format(isi, jumlah))

Hasil penjumlahan pada iterator ke-1 adalah 56
Hasil penjumlahan pada iterator ke-2 adalah 58
Hasil penjumlahan pada iterator ke-3 adalah 61
Hasil penjumlahan pada iterator ke-4 adalah 65
Hasil penjumlahan pada iterator ke-5 adalah 70
Hasil penjumlahan pada iterator ke-6 adalah 76
Hasil penjumlahan pada iterator ke-7 adalah 83
Hasil penjumlahan pada iterator ke-8 adalah 91
Hasil penjumlahan pada iterator ke-9 adalah 100
Hasil penjumlahan pada iterator ke-10 adalah 110


In [ ]:
for isi in angka:
    jumlah = jumlah + isi
print('Hasil penjumlahan adalah', jumlah)

Hasil penjumlahan adalah 165


In [ ]:
for item in 'saya belajar python':
    if (item== 'a'):
      print('hey kamu berada di huruf A, selamat!')

hey kamu berada di huruf A, selamat!
hey kamu berada di huruf A, selamat!
hey kamu berada di huruf A, selamat!
hey kamu berada di huruf A, selamat!


In [ ]:
jumlah = 0
for item in 'saya belajar python':
    jumlah += 1
    if (item== 'a'):
      print('hey kamu berada di huruf A, selamat!', jumlah)

hey kamu berada di huruf A, selamat! 2
hey kamu berada di huruf A, selamat! 4
hey kamu berada di huruf A, selamat! 9
hey kamu berada di huruf A, selamat! 11


In [ ]:
angka = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
for item in angka:
    if (item % 2 == 0):
        print('{} adalah bilangan genap'.format(item))
    else:
        print('{} adalah bilangan ganjil'.format(item))

1 adalah bilangan ganjil
2 adalah bilangan genap
3 adalah bilangan ganjil
4 adalah bilangan genap
5 adalah bilangan ganjil
6 adalah bilangan genap
7 adalah bilangan ganjil
8 adalah bilangan genap
9 adalah bilangan ganjil
10 adalah bilangan genap


In [ ]:
for item in angka:
    if (item % 2 == 0):
        print('Angka',item, 'adalah bilangan genap')
    else:
        print('Angka '+str(item)+' adalah bilangan ganjil')

Angka 1 adalah bilangan ganjil
Angka 2 adalah bilangan genap
Angka 3 adalah bilangan ganjil
Angka 4 adalah bilangan genap
Angka 5 adalah bilangan ganjil
Angka 6 adalah bilangan genap
Angka 7 adalah bilangan ganjil
Angka 8 adalah bilangan genap
Angka 9 adalah bilangan ganjil
Angka 10 adalah bilangan genap


In [ ]:
box1 = ((1,2),(3,4),(5,6))

In [ ]:
for item in box1:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [ ]:
for a,b in box1:
    print(a,b)

1 2
3 4
5 6


In [ ]:
for a,b in box1:
    print(a)
    print(b)

1
2
3
4
5
6


In [ ]:
box2 = [[1,2],[3,4],[5,6]]

In [ ]:
for a,b in box2:
    print(a)
    print(b)

1
2
3
4
5
6


In [ ]:
box3 = [[1,2,'a'],[3,4,'b'],[5,6,'c']]

In [ ]:
for i,j,k in box3:
  print(k)

a
b
c


In [ ]:
indeks = 0
while True:
    print('saya berhasil menjalankan while loop')
    indeks += 1
    if indeks == 10:
      break

saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop
saya berhasil menjalankan while loop


In [ ]:
x = 0

In [ ]:
while x < 50:
    print('Bilangan x saat ini adalah: ',x)
    x += 2

Bilangan x saat ini adalah:  0
Bilangan x saat ini adalah:  2
Bilangan x saat ini adalah:  4
Bilangan x saat ini adalah:  6
Bilangan x saat ini adalah:  8
Bilangan x saat ini adalah:  10
Bilangan x saat ini adalah:  12
Bilangan x saat ini adalah:  14
Bilangan x saat ini adalah:  16
Bilangan x saat ini adalah:  18
Bilangan x saat ini adalah:  20
Bilangan x saat ini adalah:  22
Bilangan x saat ini adalah:  24
Bilangan x saat ini adalah:  26
Bilangan x saat ini adalah:  28
Bilangan x saat ini adalah:  30
Bilangan x saat ini adalah:  32
Bilangan x saat ini adalah:  34
Bilangan x saat ini adalah:  36
Bilangan x saat ini adalah:  38
Bilangan x saat ini adalah:  40
Bilangan x saat ini adalah:  42
Bilangan x saat ini adalah:  44
Bilangan x saat ini adalah:  46
Bilangan x saat ini adalah:  48


In [ ]:
angka = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
for item in angka:
    if item %2 == 0:
        continue
    else:
        print('Anda berada di angka ganjil =', item)

Anda berada di angka ganjil = 1
Anda berada di angka ganjil = 3
Anda berada di angka ganjil = 5
Anda berada di angka ganjil = 7
Anda berada di angka ganjil = 9


In [ ]:
for item in angka:
    if item %2 != 0:
        continue
    else:
        print('Anda berada di angka genap =', item)

Anda berada di angka genap = 2
Anda berada di angka genap = 4
Anda berada di angka genap = 6
Anda berada di angka genap = 8
Anda berada di angka genap = 10


In [ ]:
for i in 'Saya sudah mulai mahir di Python':
    if i == 'a':
        pass
    else:
        continue

In [ ]:
for i in 'abcd':
    pass

**14 to 52
Usefull Operators & For Loops -Advanced-**

Range

In [ ]:
for item in range(0,10):
    print(item)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#for item in range 0-20(angka 20 tidak dimasukkan), dan melompat sebanyak 3 karakter
for item in range(0,20,3):
    print(item)

0
3
6
9
12
15
18


In [ ]:
#cara 1
angka = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
angka

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#cara 2
angka2 = list(range(1,11))

In [ ]:
angka2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Enumerate (datanya dalam bentuk tuple)

In [ ]:
#tanpa enumerate

indeks = 0
for item in 'abcdefghij':
    print('karakter {} berada di indeks ke- {}'.format(item,indeks))
    indeks += 1

karakter a berada di indeks ke- 0
karakter b berada di indeks ke- 1
karakter c berada di indeks ke- 2
karakter d berada di indeks ke- 3
karakter e berada di indeks ke- 4
karakter f berada di indeks ke- 5
karakter g berada di indeks ke- 6
karakter h berada di indeks ke- 7
karakter i berada di indeks ke- 8
karakter j berada di indeks ke- 9


In [ ]:
#dengan enumerate

kata = 'abcdefghij'
for item in enumerate(kata):
    print(item)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')
(4, 'e')
(5, 'f')
(6, 'g')
(7, 'h')
(8, 'i')
(9, 'j')


In [ ]:
nama = 'idar'
for item in enumerate(nama):
    print(item)

(0, 'i')
(1, 'd')
(2, 'a')
(3, 'r')


In [ ]:
for a,b in enumerate(nama):
    print(a)
    print(b)

0
i
1
d
2
a
3
r


In [ ]:
for a,b in enumerate(nama):
    print(a,b)

0 i
1 d
2 a
3 r


Zip (datanya tuple)

In [ ]:
list1 = [1,2,3,4,5]
list2 = ['a','b','c','d','e']

In [ ]:
for item in zip (list1, list2):
    print(item)

(1, 'a')
(2, 'b')
(3, 'c')
(4, 'd')
(5, 'e')


In [ ]:
list1 = [1,2,3,4,5]
list2 = ['a','b','c','d','e']
list3 = [100,200,300,400,500]

In [ ]:
for item in zip (list1, list2, list3):
    print(item)

(1, 'a', 100)
(2, 'b', 200)
(3, 'c', 300)
(4, 'd', 400)
(5, 'e', 500)


In [ ]:
list(zip(list1,list2))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]

In [ ]:
list(zip(list1, list2, list3))

[(1, 'a', 100), (2, 'b', 200), (3, 'c', 300), (4, 'd', 400), (5, 'e', 500)]

**Item checking**

utk berbagai macam tipe data, sangat berguna untuk melakukan checking pada data orang lain di bidang data science

In [ ]:
'aku belajar'

'aku belajar'

In [ ]:
'k' in 'aku belajar'

True

In [ ]:
'v' in 'aku belajar'

False

In [ ]:
#pada contoh ini menggunakan data berbentuk dictionary jadi harus menggunakan tanda kurung {}

kotak1 = {'a':100, 'b':200, 'c':300}

In [ ]:
'c' in kotak1 #ini digunakan untuk mengecek key pada data berbentuk dictionary

True

In [ ]:
200 in kotak1 #ini bernilai false karna angka 200 merupakan value/nilai dari key 'b'

False

In [ ]:
200 in kotak1.values() #kode ini digunakan untuk mengecek value/nilai dari sebuah key dalam data berbentuk dictionary

True

In [ ]:
250 in kotak1.values()

False

Advanced For Loops

In [ ]:
isi = [] #data 'isi' tidak ada isinya

In [ ]:
#cara 1 untuk mengisi data di dalam 'isi' menggunakan metode dibawah ini

isi = list(range(1,11))

In [ ]:
isi

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#cara 2 untuk mengisi data di dalam 'isi' menggunakan metode dibawah ini

isi2 = list()
for item in range(1,11):
    isi2.append(item)
isi2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#cara untuk mepersingkat cara ke 2 di atas

isi3 = [item for item in range(1,11)]

In [ ]:
isi3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
isi4 = [item**2 for item in range (1,11)]
isi4

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
isi5 = [item*2 for item in range (1,11)]
isi5

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
isi6 = [item**2/3 for item in range (1,11)]
isi6

[0.3333333333333333,
 1.3333333333333333,
 3.0,
 5.333333333333333,
 8.333333333333334,
 12.0,
 16.333333333333332,
 21.333333333333332,
 27.0,
 33.333333333333336]

In [ ]:
#klo menggunakan if, penulisan if ditulis dibelakang

isi7 = [item for item in range (1,11) if item %2 == 0]
isi7

[2, 4, 6, 8, 10]

In [ ]:
#klo menggunakna if dan else, maka penulisan if dan else ditulis di depan

isi8 = [item if item%2==0 else 'angka ini bilangan ganjil' for item in range (1,11)]
isi8

['angka ini bilangan ganjil',
 2,
 'angka ini bilangan ganjil',
 4,
 'angka ini bilangan ganjil',
 6,
 'angka ini bilangan ganjil',
 8,
 'angka ini bilangan ganjil',
 10]

In [ ]:
#menggunakan cara yang lain, tapi outputnya akan sama dengan langkah diatas
isi9 = []
for item in range(1,11):
    if item %2 == 0:
        isi9.append(item)
    else:
        isi9.append('angka ini bilangan ganjil')

In [ ]:
isi9

['angka ini bilangan ganjil',
 2,
 'angka ini bilangan ganjil',
 4,
 'angka ini bilangan ganjil',
 6,
 'angka ini bilangan ganjil',
 8,
 'angka ini bilangan ganjil',
 10]

**Functions, ARGS & KWARGS**

Functions

**def** nama_fungsinya(variabel):
'''
docstring = sebuah komentar untuk pembaca
'''

    perintah yang diinginkan
    return/print


*   Return digunakan untuk mendefinisikan hasil fungsi ke variabel
*   Print digunakan jika hanya ingin mencetak hasil dari fungsinya

In [ ]:
4+5

9

In [ ]:
7*90

630

In [ ]:
def cetak_kalimat():
    print('ternyata belajar Python itu mudah')

In [ ]:
cetak_kalimat #klo lupa menggunakan tanda kurung, maka hasilnya seperti dibawah ini

<function __main__.cetak_kalimat()>

In [ ]:
cetak_kalimat()

ternyata belajar Python itu mudah


In [ ]:
list1 = list(range(1,10))

In [ ]:
list1.append

<function list.append(object, /)>

In [ ]:
list1.append(3)

In [ ]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 3]

In [ ]:
def perkalian(num1,num2):
    return num1*num2

In [ ]:
kali = perkalian(6,7)
kali

42

In [ ]:
def perkalian(num1,num2,num3):
    return num1*num2*num3

In [ ]:
kali = perkalian(6,7,2)
kali

84

In [ ]:
def penjumlahan(num1,num2):
    print(num1+num2)

In [ ]:
jumlah = penjumlahan(1,3)

4


In [ ]:
type(jumlah)

NoneType

In [ ]:
def belajar(nama='Python'):
    print('Saya sedang belajar '+nama)

In [ ]:
belajar('Matematika')

Saya sedang belajar Matematika


In [ ]:
def belajar(var='Python'):
    print('Saya sedang belajar '+var)

In [ ]:
belajar()

Saya sedang belajar Python


In [ ]:
def deteksi_genap(var1):
    '''
    Ini adalah fungsi untuk membedakan ganjil genap
    '''
    if (var1 %2 == 0):
        print('Ini adalah angka genap')
    else:
        print('Ini adalah angka ganjil')

In [ ]:
deteksi_genap(7)

Ini adalah angka ganjil


In [ ]:
#Tantangan Fungsi
'''
Buatlah sbeuah fungsi yang bisa memberikan nilai True jika bisa menemukan kata 'Python'

Contoh kalimatnya: "Ternyata belajar Python itu mudah!"
Contoh kalimat juga bisa diubah-ubah sesuai keinginan
'''

In [ ]:
kalimat = input('Masukkanlah kalimat yang diinginkan ')

Masukkanlah kalimat yang diinginkan saya


In [ ]:
kalimat

'saya'

In [ ]:
#cara 1

def cetak_kalimat(var):
    if 'Python' in var:
        return True
    else:
        return False

In [ ]:
cetak_kalimat(kalimat)

False

In [ ]:
'Nama' in 'Nama saya adalah Mega'

True

In [ ]:
#cara 2

def cetak_kalimat(var):
    return 'Python' in var.lower()

In [ ]:
cetak_kalimat(kalimat)

False

*Args(argumen) dan **Kwargs(key word argumen)

In [ ]:
def jumlah(a,b,c):
    return a+b+c

In [ ]:
jumlah(8,9,1)

18

In [ ]:
def kurang(a,b,c,d):
    return a-b-c-d

In [ ]:
kurang(9,3,2,1)

3

In [ ]:
def bagi(a,b):
    return(a/b)

In [ ]:
bagi(6,2)

3.0

In [ ]:
#untuk menyederhanakan beberapa cara di atas

def jumlah(*args):
    return sum((args))

In [ ]:
jumlah(8,9,1,100,4,7,2)

131

In [ ]:
def cek_args(*args):
    print(args)

In [ ]:
cek_args(2,3,4,5,6,7)

(2, 3, 4, 5, 6, 7)


In [ ]:
sum((2,3,4,5,6,7))

27

In [ ]:
sum([1,2,3,4])

10

In [ ]:
def cek_kwargs(**kwargs):
    print(kwargs)

In [ ]:
cek_kwargs(anak='gemuk')

{'anak': 'gemuk'}


In [ ]:
cek_kwargs(anak=86)

{'anak': 86}


In [ ]:
def cek_berat(**kwargs):
    if 'Budi' in kwargs:
        print('Berat Budi tergolong ke kategori {}'.format(kwargs['Budi']))
    else:
        print('Budi tidak termasuk ke database kita')

In [ ]:
cek_berat(Budi='gemuk')

Berat Budi tergolong ke kategori gemuk


In [ ]:
cek_berat(Budi='gemuk', Joko='kurus')

Berat Budi tergolong ke kategori gemuk


Menggabungkan *args dan **kwargs

In [ ]:
  def fungsiku(*args,**kwargs):
      print('Saya ingin membeli {} {} secara tunai'.format(args[0], kwargs['makanan']))

In [ ]:
fungsiku(23, 56, 10, buah='apel', makanan='nasi goreng')

Saya ingin membeli 23 nasi goreng secara tunai


**SCOPE & L-E-G-B**

In [ ]:
a = 1000

def jumlah():
    a = 79
    return a

In [ ]:
print(a)

1000


In [ ]:
print(jumlah())

79


Urutan eksekusi Python

*   L (Local) = variabel ini bersifat lokal, yang biasanya berada di dalam fungsi (def/lamda) tertentu.
*   E (Enclosing function local) = variabel ini berada di dalam fungsi (def/lamda) mulai dari lingkup terdalam hingga keluar.
*   G (Global) = variabel ini didefinisikan di luar, biasanya di tahap awal.
*   B (Built-in) = variabel bawaan Python, seperti list, str, upper, dll.

In [ ]:
kalimat = 'Saya adalah GLOBAL'

def cetak():
    kalimat = 'Saya adalah LOCAL'

    def eksekusi():
        print('Halo hasilnya adalah '+kalimat)

    eksekusi()

In [ ]:
cetak()

Halo hasilnya adalah Saya adalah LOCAL


In [ ]:
kalimat = 'Saya adalah GLOBAL'

def cetak():
    # kalimat = 'Saya adalah LOCAL'

    def eksekusi():
        print('Halo hasilnya adalah '+kalimat)

    eksekusi()

In [ ]:
cetak()

Halo hasilnya adalah Saya adalah GLOBAL


In [ ]:
kalimat = 'Saya adalah GLOBAL'

def cetak():
    kalimat = 'Saya adalah LOCAL'

    def eksekusi():
        kalimat = 'Saya itu LOCAL BANGET'
        print('Halo hasilnya adalah '+kalimat)

    eksekusi()

In [ ]:
cetak()

Halo hasilnya adalah Saya itu LOCAL BANGET


In [ ]:
angka = 99

def tulis(angka):
    print(f'Angka = {angka}') #penulisan ini sama dengan print('Angka = {}'.format{angka})

In [ ]:
tulis(angka)

Angka = 99


In [ ]:
angka = 99

def tulis(angka):
    print(f'Angka = {angka}') #penulisan ini sama dengan print('Angka = {}'.format{angka})

    #mendefinisikan ulang sebuah variabel di fungsi
    angka = 300
    print(f'Angkanya sekarang saya ubah menjadi {angka}')

In [ ]:
print(angka)

99


In [ ]:
angka = 99

def tulis():
    global angka

    #mendefinisikan ulang sebuah variabel di fungsi
    angka = 'GANTI LO'
    print(f'Angkanya sekarang saya ubah menjadi {angka}')

In [ ]:
tulis()

Angkanya sekarang saya ubah menjadi GANTI LO


In [ ]:
print(angka)

GANTI LO


In [ ]:
angka = 99

def tulis(angka):

    #mendefinisikan ulang sebuah variabel di fungsi
    angka = 'GANTI LO'
    print(f'Angkanya sekarang saya ubah menjadi {angka}')
    return angka

In [ ]:
print(angka)

99


**MAP, Filter & Lambda**

In [ ]:
#MAP

def kali10(num):
    return num*10

In [ ]:
kali10(76)

760

In [ ]:
angka = [3,6,9]

In [ ]:
kali10(angka)
#fungsi ini membuat semua variabel di dalam angka muncul sebanyak 10 kali

[3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9,
 3,
 6,
 9]

In [ ]:
for item in map(kali10, angka):
    print(item)

30
60
90


In [ ]:
list(map(kali10,angka))

[30, 60, 90]

In [ ]:
hasil = list(map(kali10,angka))
hasil

[30, 60, 90]

In [ ]:
angka2 = (31,61,91)

In [ ]:
hasil2 = tuple(map(kali10, angka2))

In [ ]:
hasil2

(310, 610, 910)

In [ ]:
def jumlahkata(kata):
    if len(kata)%2 == 0:
        return 'GENAP LHO'
    else:
        return 'GANJIL LHO'

In [ ]:
jumlahkata('hdjjieikdhdjvjvdd')

'GANJIL LHO'

In [ ]:
listkata = ['jdkljdkl','diuhiuf','hieuheig']

In [ ]:
list(map(jumlahkata,listkata))

['GENAP LHO', 'GANJIL LHO', 'GENAP LHO']

In [ ]:
# FILTER

def cekgenap(num):
    return num%2 == 0

In [ ]:
cekgenap(7)

False

In [ ]:
nomor = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
list(filter(cekgenap, nomor)) #hasilnya dalam bentuk list

[2, 4, 6, 8, 10]

In [ ]:
for item in filter(cekgenap, nomor):  #hasilnya dalam bentuk menurun
    print(item)

2
4
6
8
10


In [ ]:
# map dan filter

**Lambda Expression**

In [ ]:
def kali10a(num):
    return num*10

In [ ]:
kali10a(6)

60

In [ ]:
fungsiku = lambda x: x*10

In [ ]:
fungsiku(60)

600

In [ ]:
hasila = list(map(lambda x: x*10, angka))

In [ ]:
hasila

[30, 60, 90]

In [ ]:
genapku = list(filter(lambda num: num%2 == 0, nomor))

In [ ]:
genapku

[2, 4, 6, 8, 10]

### **Object Oriented Programming**

In [ ]:
# Di Python semua adalah objek, seperti; lists, strings, dictionary, dll.
# Di Python, objek disebut dengan istilah class.

#Setelah mendefinisikan objek, kita bisa menggunakan methods dan attributes terhadap objek tersebut.

#OOP memungkinkan programmer untuk menciptakan objek mereka sendiri, termasuk methods dan attributes-nya.

#OOP memungkinkan kita membuat objek kita sendiri, termasuk methods dan attributes nya

In [ ]:
print(type([]))
print(type({}))
print(type('saya adalah string'))
print(type(12))
print(type(13.98))
print(type(()))
print(type(True))
print(type(None))

<class 'list'>
<class 'dict'>
<class 'str'>
<class 'int'>
<class 'float'>
<class 'tuple'>
<class 'bool'>
<class 'NoneType'>


**Mendefinisikan Class**

class NamaClass:

    def_init_(self, nama_attribute1, nama_attribute2):
        self.nama_attribute1 = nama_attribute1
        self.nama_attribute2 = nama_attribute2

    def nama_methode(self):
      return #tulis fungsinya

In [ ]:
class Nama:
    pass

In [ ]:
var1 = Nama()

In [ ]:
type(var1)

__main__.Nama

In [ ]:
# penulisan cara 2 : bisa juga dituliskan berbeda

class Kulkas:
    def __init__(self, merek1, harga1):
        self.brand = merek1
        self.price = harga1

In [ ]:
barang1 = Kulkas('Samsung', 500) #bisa juga dituliskan seperti ini

In [ ]:
barang1.brand

'Samsung'

In [ ]:
barang1.price

500

In [ ]:
# penulisan cara 1 : dituliskan sama agar tidak membingungkan

class Kulkas:
    def __init__(self, merek, harga):
        self.merek = merek
        self.harga = harga

In [ ]:
barang1 = Kulkas(merek='Samsung', harga=500) #bisa dituliskan seperti ini

In [ ]:
barang1.merek

'Samsung'

In [ ]:
barang1.harga

500

In [ ]:
barang2 = Kulkas('Toshiba', 1200)

In [ ]:
barang2.merek
#self.merek <- self ini merepresantasikan barang2

'Toshiba'

In [ ]:
barang2.harga

1200

In [ ]:
#Bisa menambah atribut lain
class Kulkas:

    def __init__(self, merek, harga): #yang wajib didefinisikan hanya 2 attribute (merek, harga)
        self.merek = merek
        self.harga = harga
        self.garansi = 3
        self.tenaga = 'listrik'

In [ ]:
barang2 = Kulkas('LG', 2000)

In [ ]:
barang2.garansi

3

In [ ]:
barang2.tenaga

'listrik'

In [ ]:
#cara yang lain

class Kulkas:

    # class object attribute (attribute ini bersifat global untuk class Kulkas)
    penjual = 'Pak Mamat'

    def __init__(self, merek, harga):
        self.merek = merek
        self.harga = harga
        self.garansi = 3
        self.tenaga = 'listrik'

    def konsumsi(self):
        print('500 watt')

In [ ]:
barang = Kulkas('LG', 200)

In [ ]:
barang.penjual

'Pak Mamat'

In [ ]:
barang.konsumsi() #utk menjalankan definisi dibawah __init__ (konsumsi) harus ditambahkan tanda dalam kurung

500 watt


In [ ]:
#cara yang lain

class Kulkas:

    # class object attribute (attribute ini bersifat global untuk class Kulkas)
    penjual = 'Pak Mamat'

    def __init__(self, merek, harga):
        self.merek = merek
        self.harga = harga
        self.garansi = 3
        self.tenaga = 'listrik'

    def keterangan(self):
        print('Kulkas merek {} harganya sebesar {}, dan nama penjualnya {}'.format(self.merek, self.harga, self.penjual))

In [ ]:
barang = Kulkas('LG', 200)

In [ ]:
barang.keterangan()

Kulkas merek LG harganya sebesar 200, dan nama penjualnya Pak Mamat


In [ ]:
#cara yang lain

class Kulkas:

    # class object attribute (attribute ini bersifat global untuk class Kulkas)
    penjual = 'Pak Mamat'

    def __init__(self, merek, harga):
        self.merek = merek
        self.harga = harga
        self.garansi = 3
        self.tenaga = 'listrik'

    def keterangan(self, anak):
        print('Kulkas merek {} harganya sebesar {}, dan nama penjualnya {} yang punya {} anak'.format(self.merek, self.harga, self.penjual, anak))

In [ ]:
barang = Kulkas('LG', 200)

In [ ]:
barang.keterangan(5)

Kulkas merek LG harganya sebesar 200, dan nama penjualnya Pak Mamat yang punya 5 anak


In [ ]:
#menghitung Luas Lingkaran

class Lingkaran:

    # koefisien phi
    phi = 3.14

    def __init__(self, radius):
        self.radius = radius

    def keliling(self): #cara 1 penulisan def keliling
        self.keliling = 2*self.phi*self.radius
        return self.keliling

    def keliling(self): #cara 2 penulisan def keliling
        return 2*self.phi*self.radius

    def Luas(self):
        return self.phi*self.radius*self.radius

In [ ]:
l1 = Lingkaran(10)

In [ ]:
l1.keliling()

62.800000000000004

In [ ]:
l1.Luas()

314.0

In [ ]:
#cara yang lebih singkat dalam menghitung Luas Lingkaran

class Lingkaran:

    # koefisien phi
    phi = 3.14

    def __init__(self, radius):
        self.radius = radius
        self.luas = 2*self.phi*radius*radius

    def keliling(self): #cara 2 penulisan def keliling
        return 2*self.phi*self.radius

In [ ]:
l1 = Lingkaran(7)

In [ ]:
l1.luas #ini tidak ditambahkan tanda kurung setelah kata luas karena luas sudah ada di def pertama

307.72

**Inheritance**

In [ ]:
class Mahasiswa:

    status = 'Mahasiswa'

    def __init__(self, nama, kelas):
        self.nama = nama
        self.kelas = kelas

    def keterangan(self):
        print('{} di kelas {} adalah seorang {}'.format(self.nama, self.kelas, self.status))

In [ ]:
Idar = Mahasiswa('Idar', 'IF 2025')

In [ ]:
Idar.keterangan()

Idar di kelas IF 2025 adalah seorang Mahasiswa


In [ ]:
class Nilai(Mahasiswa):

     def __init__(self, nama, kelas):
        super().__init__(nama, kelas) #fungsi ini sama dengan Mahasiswa.__init__(nama, kelas), tidak butuh menuliskan slef karna self sudah masuk ke dalam super
        self.nilai_update = []

     def input_nilai(self, tambah):
        self.nilai_update.append(tambah)

In [ ]:
Idar = Nilai('Idar', 'IF 2025')

In [ ]:
Idar.input_nilai(99)

In [ ]:
Idar.keterangan()

Idar di kelas IF 2025 adalah seorang Mahasiswa


In [ ]:
Idar.nilai_update

[99]

**Polymorphism**

Fitur dari sebuah kelas/beberapa kelas bisa digunakan ke dalam sebuah fungsi dimana fungsi memiliki karakter dari objek yang dia pakai.

In [ ]:
class Kucing:

    def __init__(self, nama):
        self.nama = nama

    def respon(self):
        return self.nama + ' Meong-Meong!'

In [ ]:
class Anjing:

    def __init__(self, nama):
        self.nama = nama

    def respon(self):
        return self.nama + ' Guk-Guk!'

In [ ]:
anta = Kucing('Anta')

In [ ]:
doggie = Anjing('Doggie')

In [ ]:
anta.respon()

'Anta Meong-Meong!'

In [ ]:
doggie.respon()

'Doggie Guk-Guk!'

In [ ]:
for binatang in [anta, doggie]:
    print(type(binatang))
    print(binatang.respon())

<class '__main__.Kucing'>
Anta Meong-Meong!
<class '__main__.Anjing'>
Doggie Guk-Guk!


In [ ]:
#bisa juga menggunakan cara ini

def  hewan_ngomong(binatang):
    print(binatang.respon())

In [ ]:
hewan_ngomong(anta)

Anta Meong-Meong!


**Dunder/Magic Methods**


In [ ]:
class Coba:

    def __init__(self, nama):
        self.nama = nama

    def cetak(self):
        return self.nama

In [ ]:
coba = Coba('testing')

In [ ]:
coba.cetak()

'testing'

In [ ]:
print(dir(coba))
#ini adalah sekian banyak methode yang tersembunyi, semua methods ini adalah dunder methods artinya methods ini dimungkinkan digunakan oleh ojek 'Coba', tapi tidak disarankan untuk mengubah kecuali tau tujuannya.

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cetak', 'nama']


In [ ]:
# Change from ___str__ to __str__
coba.__str__()

'<__main__.Coba object at 0x7fa9529ea890>'

In [ ]:
str(coba)

'<__main__.Coba object at 0x7fa9529ea890>'

In [ ]:
#menambahkan def str

class Coba:

    def __init__(self, nama, angka, kata):
        self.nama = nama
        self.angka = angka
        self.kata = kata

    def cetak(self):
        return self.nama

    def __str__(self):
        return self.nama

In [ ]:
coba = Coba('Idar',20,'sehat')

In [ ]:
coba.cetak()

'Idar'

In [ ]:
str(coba)

'Idar'

Tantangan OOP


Buatlah sebuah class dengan nama RekeningBank.

Kemudian class ini memiliki method seperti mencetak saldo, menabung dan menarik uang.

Jika rekeningnya kurang, maka akan menunjukkan bahwa saldo tidak bisa ditarik karena tidak mencukupi.

In [ ]:
class RekeningBank:

    def __init__(self, tabungan):
         self.tabungan = tabungan

    def cek_saldo(self):
        print('Jumlah saldo Anda adalah = Rp.{}'.format(self.tabungan))

    def menabung(self, jumlah):
        tambah = int(input('Masukkan jumlah yang ingin ditabung = '))
        self.tabungan += jumlah #self.tabungan = self.tabungan + tambah

    def menarik(self):
        kurang = int(input('Masukkan jumlah yang ingin ditarik = '))
        if self.tabungan < kurang:
            print('Maaf saldo Anda tidak mencukupi \nSaldo Anda saat ini adalah {}'.format(self.tabungan))
        else:
            self.tabungan -= kurang # self.tabungan = self.tabungan - kurang

In [ ]:
tabunganku = RekeningBank(10000)

In [ ]:
tabunganku.cek_saldo()

Jumlah saldo Anda adalah = Rp.10000


In [ ]:
tabunganku.menabung()

Masukkan jumlah yang ingin ditabung = 100000


In [ ]:
tabunganku.cek_saldo()

Jumlah saldo Anda adalah = Rp.20000


In [ ]:
tabunganku.menarik()

Masukkan jumlah yang ingin ditarik = 50000
Maaf saldo Anda tidak mencukupi 
Saldo Anda saat ini adalah 20000


## Numpy

Apa itu Numpy?


*   Library aljabar linear untuk Python
*   Numpy sering dipakai dalam konteks AI & Data Science
*   Numpy sangat cepat dan dibangun melalui Bahasa C



Menginstall Numpy


*   Direkomendasikan melalui Anaconda
*   Anaconda prompt -> conda install numpy
*   Command line -> pip install numpy

In [ ]:
import numpy as np

In [ ]:
angka = [1,2,3]

In [ ]:
angkanp = np.array(angka)

In [ ]:
angkanp

array([1, 2, 3])

In [ ]:
angka*3 #ini output klo menggunakan list

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
angkanp*3 #nilai dalam np dikali 3, hasil menjadi 1 baris vektor

array([3, 6, 9])

In [ ]:
varsilist = [[1,2,3],[4,5,6],[7,8,9]]
varsilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
versinumpy = np.array(varsilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [ ]:
np.linspace(0,2,1)

array([0.])

**Identity Matrix**

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Numpy Part 2**

Indexing & Slicing

In [ ]:
import numpy as np

In [ ]:
#bilangan distribusi uniform (0-1)

np.random.rand(7)

array([0.9430404 , 0.35310772, 0.49585491, 0.49003311, 0.28918018,
       0.78481795, 0.75237657])

In [ ]:
#bilangan distribusi uniform (0-1) matriks 2 dimensi

np.random.rand(5,4)

array([[0.32995662, 0.72208551, 0.94103167, 0.69664089],
       [0.93149092, 0.3195989 , 0.35749949, 0.86339548],
       [0.7976556 , 0.10361218, 0.3358437 , 0.95003403],
       [0.94313565, 0.96489952, 0.71740039, 0.1716357 ],
       [0.81630789, 0.01739791, 0.4367334 , 0.07346792]])

In [ ]:
# distribusi normal (gaussian)

np.random.randn(5) #cara penulisannya sama hanya ditambahkan n pada rand pada distribusi normal(gaussian)

array([-0.87986571, -0.53294165,  2.54447308, -0.05194882,  0.47129464])

In [ ]:
# distribusi normal (gaussian)

np.random.randn(10)

array([ 1.68276027,  1.06220522,  0.70738563,  0.51514772, -0.21635772,
        1.80855686, -0.70951596, -1.84303481, -1.21013599,  0.22266846])

In [ ]:
# distribusi normal (gaussian) matriks 2 dimensi

np.random.randn(4,4)

array([[-0.75433593,  1.52085837,  0.15307786,  0.66392102],
       [-0.59225873,  0.63437998, -0.27689287, -1.03059283],
       [ 1.17607021,  0.61936595,  1.44273958,  0.82735413],
       [ 0.50051465, -0.46258429, -0.02994889,  0.68322734]])

In [ ]:
from numpy.random import randn

In [ ]:
randn(6,2)

array([[ 0.85521715, -0.44094841],
       [ 1.91167773,  0.05438929],
       [-0.7166812 , -0.94198647],
       [ 0.86439113,  0.52548829],
       [ 0.2906774 ,  0.9232103 ],
       [ 1.09517675, -1.47785924]])

In [ ]:
from numpy.random import randn, randint

In [ ]:
randn(4,2)

array([[-0.401648  , -1.01085134],
       [-0.29302252,  0.90420697],
       [-0.36017736,  0.01523509],
       [-0.73593935,  0.42385425]])

In [ ]:
randint(0,10)

1

In [ ]:
randn(6,2)

array([[-1.93029713e+00, -3.86145471e-01],
       [ 5.15762123e-01, -8.49205062e-01],
       [ 3.18555130e-01,  5.15907505e-01],
       [-6.03054868e-01, -3.24326047e-01],
       [ 1.18654619e+00,  1.86739805e-03],
       [-1.05597864e+00,  1.34574255e-01]])

In [ ]:
randint(0,10)

9

In [ ]:
randint(0,10,5)

array([1, 0, 5, 6, 2])

In [ ]:
bilangan = randint(0,100,20)

In [ ]:
bilangan

array([19, 20, 33, 88, 77, 11, 66, 89, 14, 48, 72, 81, 27, 36, 20,  9, 76,
       18, 32, 41])

In [ ]:
bilangan.reshape(4,5) #untuk mengubah dari vektor 1 baris menjadi beberapa baris yang diinginkan

array([[19, 20, 33, 88, 77],
       [11, 66, 89, 14, 48],
       [72, 81, 27, 36, 20],
       [ 9, 76, 18, 32, 41]])

In [ ]:
bilangan.reshape(2,10)

array([[19, 20, 33, 88, 77, 11, 66, 89, 14, 48],
       [72, 81, 27, 36, 20,  9, 76, 18, 32, 41]])

In [ ]:
bilangan.reshape(5,4)

array([[19, 20, 33, 88],
       [77, 11, 66, 89],
       [14, 48, 72, 81],
       [27, 36, 20,  9],
       [76, 18, 32, 41]])

In [ ]:
randint(0,10,15)

array([3, 2, 2, 6, 1, 8, 9, 0, 7, 3, 8, 9, 8, 3, 4])

In [ ]:
coba = randint(0,10,15).reshape(3,5)

In [ ]:
coba

array([[4, 0, 4, 6, 9],
       [4, 0, 9, 0, 5],
       [9, 4, 8, 7, 9]])

In [ ]:
coba.reshape(5,3)

array([[4, 0, 4],
       [6, 9, 4],
       [0, 9, 0],
       [5, 9, 4],
       [8, 7, 9]])

In [ ]:
coba #klo tidak didefine ulang maka akan kembali ke matriks awal

array([[4, 0, 4, 6, 9],
       [4, 0, 9, 0, 5],
       [9, 4, 8, 7, 9]])

In [ ]:
coba = coba.reshape(5,3)

In [ ]:
coba

array([[4, 0, 4],
       [6, 9, 4],
       [0, 9, 0],
       [5, 9, 4],
       [8, 7, 9]])

In [ ]:
from numpy.random import rand, randn, randint

In [ ]:
coba1d = randint(0,100,20)

In [ ]:
coba2d = randint(0,100,20).reshape(4,5)

In [ ]:
coba1d

array([15, 90, 15, 64, 39, 36, 91, 20, 20, 54, 55, 74, 62,  4, 16, 15, 87,
        2, 59, 51])

In [ ]:
coba2d

array([[91, 63, 66, 27,  9],
       [43, 11, 28, 35, 21],
       [43, 87, 39, 37, 43],
       [ 1, 11, 24, 49, 68]])

In [ ]:
coba1d.max() #untuk melihat nilai yg paling besar dari matriks

np.int64(91)

In [ ]:
coba2d.max() #untuk melihat nilai yg paling besar dari matriks

np.int64(91)

In [ ]:
coba1d.min()

np.int64(2)

In [ ]:
coba2d.min()

np.int64(1)

In [ ]:
#argmax dan argmin sangat berguna untuk machine learning

coba1d.argmax() #argmax digunakan untuk  mencari indeks (posisi) elemen dengan nilai terbesar dalam sebuah array atau list.

np.int64(6)

In [ ]:
coba2d.argmax() #argmax digunakan untuk  mencari indeks (posisi) elemen dengan nilai terbesar dalam sebuah array atau list.

np.int64(0)

In [ ]:
coba1d.argmin() #argmin digunakan untuk  mencari indeks (posisi) elemen dengan nilai terkecil dalam sebuah array atau list.

np.int64(17)

In [ ]:
coba2d.min() #argmin digunakan untuk  mencari indeks (posisi) elemen dengan nilai terkecil dalam sebuah array atau list.

np.int64(1)

In [ ]:
coba1d.shape #digunakan untuk mengetahui jenis matriksnya

(20,)

In [ ]:
coba2d.shape

(4, 5)

In [ ]:
coba1d.dtype #digunakan untuk mengetahui jenis data

dtype('int64')

**Indexing di Numpy**

In [ ]:
import numpy as np

In [ ]:
coba = np.arange(0,11)

In [ ]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
coba[6]

np.int64(6)

In [ ]:
coba[9]

np.int64(9)

In [ ]:
coba1 = np.arange(0,20,2)

In [ ]:
coba1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
coba1[3]

np.int64(6)

In [ ]:
coba1[5:]

array([10, 12, 14, 16, 18])

In [ ]:
coba1[3:7]

array([ 6,  8, 10, 12])

In [ ]:
coba1[:4]

array([0, 2, 4, 6])

In [ ]:
coba2 = coba[:6] #ini mengubah data pada coba

In [ ]:
coba2

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
coba2[:] = 100 #mengubah semua data di dalam coba2 menjadi 100

In [ ]:
coba2

array([100, 100, 100, 100, 100, 100])

In [ ]:
coba

array([100, 100, 100, 100, 100, 100,  12,  14,  16,  18])

In [ ]:
# untuk tidak mengubah data pada data 'coba' menggunakan cara seperti dibawah ini

coba = np.arange(0,11)

In [ ]:
# untuk tidak mengubah data pada data 'coba' menggunakan cara seperti dibawah ini

coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# untuk tidak mengubah data pada data 'coba' menggunakan cara seperti dibawah ini

coba2 = coba.copy()

In [ ]:
coba2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
coba2[:]=200

In [ ]:
coba2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [ ]:
coba #data pada coba tidak berubah

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bil2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
bil2d[0][0] #ini digunakan untuk memanggil angka 1, di posisi bil2d[baris][kolom], indeks dimulai dari 0

np.int64(1)

In [ ]:
bil2d[1] #ini digunakan untuk memanggil angka di baris ke-1, indeks dimulai dari 0

array([4, 5, 6])

In [ ]:
bil2d[2,2] #ini digunakan untuk memanggil angka pada posisi baris 2, kolom 2, indeks dimulai dari 0

np.int64(9)

In [ ]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
bil2d[1:2,1:]

array([[5, 6]])

In [ ]:
bil2d[1:2,1:2] #kenapa hanya angka 5 yang dimasukkan karena kalo penulisannya 1:2 artinya yang diambil hanya kolom 1 sebelum kolom 2.

array([[5]])

**Slicing dengan boolean Numpy**

In [ ]:
import numpy as np

In [ ]:
bil = np.arange(1,11)

In [ ]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
angkaT = bil>5

In [ ]:
angkaT

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
bil = bil[angkaT]

In [ ]:
bil

array([ 6,  7,  8,  9, 10])

Melakukan Operasi Matematik di Numpy

In [ ]:
import numpy as np

In [ ]:
coba = np.arange(0,11)

In [ ]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
coba+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
coba+coba

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
coba_list = [0,1,2,3,4,5,6,7,8,9,10]

In [ ]:
coba_list+coba_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
coba*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
coba_list*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
coba-coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
coba-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [ ]:
coba/coba #output nan karna apa pun yang dibagi dengan angka 0 tidak bisa

<ipython-input-268-4b181eb448c2>:1: RuntimeWarning: invalid value encountered in divide
  coba/coba


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/coba

<ipython-input-269-021fa7643746>:1: RuntimeWarning: divide by zero encountered in divide
  1/coba


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
np.sqrt(coba) #akar

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Eksponen
**e = 2.7182**

In [ ]:
np.max(coba)

np.int64(10)

In [ ]:
coba.max()

np.int64(10)

In [ ]:
np.min(coba)

np.int64(0)

In [ ]:
coba.min()

np.int64(0)

In [ ]:
np.sin(coba)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(coba)

<ipython-input-278-953d5638885c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(coba)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

**numpy.org -> untuk melihat func (fungsi) dalam python**

# **Modul & Package**

Modul = sebuah script Python yang memiliki ekstensi*.py
Jupyter notebook menggunakan ekstensi *.ipynb
Package = Kumpulan dari beberapa modul

**name dan main**

if__name__== "__main__":

Kita ingin menegtahui apakah saat menjalankan module, kita menjalankan langsung di module itu atau hasil impor.